### ISSUE TITLE
SHOULD verify if the network interface supports IPv4 before using it

### ISSUE THREAD

**Issue by debbabi** [isandlaTech/cohorte-platforms#46]
On MacOS X, we have warnings on the interface awdl0 (which is used by AirPlay service). This interface does not support IPv4.

**Comment by tcalmant** [comment]
An exception appears on Windows with the interface created by VMPlayer:
- IPv4 interface
- multicast support
- **but** with an auto-IP (169.254....) => causes an error when trying to access it.

Therefore, when looking if a network interface is eligible for the multicast discovery, it is also necessary to check if it has an auto-IP.

**Comment by ogattaz** [comment]
Workaround

macbookpro112:~ user$ ifconfig awdl0
awdl0: flags=8943<UP,BROADCAST,RUNNING,PROMISC,SIMPLEX,MULTICAST> mtu 1452
	ether 12:a9:e0:38:08:9c 
	inet6 fe80::10a9:e0ff:fe38:89c%awdl0 prefixlen 64 scopeid 0x8 
	nd6 options=1<PERFORMNUD>
	media: autoselect
	status: active

sudo ifconfig awdl0 down

macbookpro112:~ user$ ifconfig awdl0
awdl0: flags=8902<BROADCAST,PROMISC,SIMPLEX,MULTICAST> mtu 1452
	ether 12:a9:e0:38:08:9c 
	nd6 options=1<PERFORMNUD>
	media: autoselect
	status: inactive

**Comment by tcalmant** [comment]
If the multicast group is IPv4:
* by default, use the double stack (IPv4 +v6)
* if network interface has only an IPv6 address: ignore it, it won't be able to handle the group
* if network interface has an Auto-IP: disable double stack, to avoid messing with invalid IPv6 addresses
* If a peer has an IPv4 address embedded in an IPv6 address format, keep its IPv4 address (it will avoid problems with AutoIP)

If the multicast group is IPv6:
* if network interface has only an IPv4: use double stack or ignore it
* If network interface has an Auto-IP (link local): no problem
