### ISSUE TITLE
Having Node level composition specification 

### ISSUE THREAD

**Issue by debbabi** [isandlaTech/cohorte-platforms#74]
- For the same application ID
- It override the Top Composer received composition for the local Node.

**Comment by ogattaz** [comment]
override or append ?

**Comment by debbabi** [comment]
Let say :
**Version 1** :  just append the existing composition with new components.
**Version 2** :  override some existing top composer component properties.

As example for V2 is composition of the LED demo : 
https://github.com/isandlaTech/cohorte-demos/blob/dev/led/led-gateway/conf/composition.js

We have a component `led-uno-wrapper` which has a property `"serial.port" : "/dev/ttyACM0"`. This property should be overrided on each raspberry having a different `serial.port` than this default one.

**Comment by ogattaz** [comment]
solved using the new composition files managment
