### ISSUE TITLE
Having "extra" directory on Cohorte nodes to add extra system bundles

### ISSUE THREAD

**Issue by debbabi** [isandlaTech/cohorte-platforms#83]
In situations where new version of Cohorte is not yet released and an application needs som extra system bundles that would be integrated in the release, users can put these bundles in this "extra" bundle of each node. When updating Cohorte platform with a new version  containing one of these extra packages, an installer can delete the extra bundle automatically.

**Comment by ogattaz** [comment]
Docker solve the case
